import snowflake.connector
import json
import os
from datetime import datetime

QUERY = """
WITH PARAMS AS (
    SELECT
        DATE_TRUNC('WEEK', CURRENT_DATE) - INTERVAL '1 WEEK'  AS LW_START,
        DATE_TRUNC('WEEK', CURRENT_DATE) - INTERVAL '2 WEEKS' AS L2W_START
),
PICKERS AS (
    SELECT
        CONCAT(COUNTRY_CODE, PICKER_ID::TEXT) AS KEYPICKER,
        FULLNAME AS PICKER_NAME
    FROM FIVETRAN.CPGS_TURBO_DS_PUBLIC.GLOBAL_PICKERS
    WHERE FULLNAME IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CONCAT(COUNTRY_CODE, PICKER_ID::TEXT) ORDER BY PICKER_ID) = 1
),
PICKING_TIMES AS (
    SELECT
        CONCAT(COUNTRY, PICKER_ID::TEXT) AS KEYPICKER,
        COUNTRY,
        WAREHOUSEID,
        ORDER_ID,
        DATE_TRUNC('WEEK', ORDER_CREATED_AT::DATE) AS SEMANA,
        PICKING AS TIEMPO_PICKING
    FROM RP_SILVER_DB_PROD.TURBO_CORE.GLOBAL_DELIVERY_TIMES
    WHERE ORDER_CREATED_AT::DATE >= (SELECT L2W_START FROM PARAMS)
      AND PICKING IS NOT NULL
),
VELOCIDAD AS (
    SELECT
        KEYPICKER, COUNTRY, WAREHOUSEID, SEMANA,
        AVG(TIEMPO_PICKING) AS AVG_PICKING,
        COUNT(DISTINCT ORDER_ID) AS ORDENES_PICKER
    FROM PICKING_TIMES
    GROUP BY 1, 2, 3, 4
),
CANCELACIONES AS (
    SELECT
        PT.KEYPICKER, PT.SEMANA,
        COUNT(DISTINCT CASE WHEN C.CATEGORY = 'Partner' THEN C.ORDER_ID END) AS CANCEL_PARTNER
    FROM PICKING_TIMES PT
    LEFT JOIN RP_SILVER_DB_PROD.TURBO_CORE.GLOBAL_CANCEL_RATE_OPS C
        ON PT.ORDER_ID = C.ORDER_ID AND C.VERTICAL = 'TURBO'
    GROUP BY 1, 2
),
STOCKOUTS AS (
    SELECT
        KEYPICKER,
        DATE_TRUNC('WEEK', ORDER_CREATED_AT::DATE) AS SEMANA,
        COUNT(DISTINCT ORDER_ID) AS ORDENES_CON_SO
    FROM RP_SILVER_DB_PROD.TURBO_CORE.GLOBAL_STOCKOUT_ORDERS
    WHERE VERTICAL_SUB_GROUP = 'TURBO'
      AND COUNT_TO_GMV = TRUE
      AND STOCKOUT_TYPE IN ('Total Ops', 'Partial Ops')
      AND ORDER_CREATED_AT::DATE >= (SELECT L2W_START FROM PARAMS)
      AND KEYPICKER IS NOT NULL
    GROUP BY 1, 2
),
DEFECTOS AS (
    SELECT
        PT.KEYPICKER, PT.SEMANA,
        COUNT(DISTINCT D.ORDER_ID) AS ORDENES_CON_DEFECTO
    FROM PICKING_TIMES PT
    LEFT JOIN RP_GOLD_DB_PROD.TURBO_CORE.GLOBAL_DASH_DEFECTS_SF D
        ON PT.ORDER_ID = D.ORDER_ID
    WHERE D.ORDER_ID IS NOT NULL
    GROUP BY 1, 2
),
BASE AS (
    SELECT
        V.KEYPICKER, V.COUNTRY, V.WAREHOUSEID, V.SEMANA, V.ORDENES_PICKER,
        ROUND(COALESCE(C.CANCEL_PARTNER, 0) * 100.0 / NULLIF(V.ORDENES_PICKER, 0), 2) AS PCT_CANCEL,
        ROUND(COALESCE(S.ORDENES_CON_SO, 0) * 100.0 / NULLIF(V.ORDENES_PICKER, 0), 2) AS PCT_SO,
        ROUND(COALESCE(D.ORDENES_CON_DEFECTO, 0) * 100.0 / NULLIF(V.ORDENES_PICKER, 0), 2) AS PCT_DEFECTO,
        ROUND(V.AVG_PICKING, 1) AS VELOCIDAD_MIN
    FROM VELOCIDAD V
    LEFT JOIN CANCELACIONES C ON V.KEYPICKER = C.KEYPICKER AND V.SEMANA = C.SEMANA
    LEFT JOIN STOCKOUTS S     ON V.KEYPICKER = S.KEYPICKER AND V.SEMANA = S.SEMANA
    LEFT JOIN DEFECTOS D      ON V.KEYPICKER = D.KEYPICKER AND V.SEMANA = D.SEMANA
),
COMPARACION AS (
    SELECT
        KEYPICKER, COUNTRY, WAREHOUSEID,
        MAX(CASE WHEN SEMANA = (SELECT LW_START FROM PARAMS)  THEN PCT_CANCEL    END) AS CANCEL_LW,
        MAX(CASE WHEN SEMANA = (SELECT L2W_START FROM PARAMS)